# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - thobashangase-pokemon-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://thobashangasecontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_263c7a759eca45ee85eb6d5a5df61ced }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bab67d15492e42baadd4a04905ecb253 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: thobashangasecontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_263c7a759eca45ee85eb6d5a5df61ced }}/pokemonappchallenge:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thobashangase-pokemon-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_570870a98fdf447595f42c133de5aa2e }}
        images: 'thobashangasecontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_263c7a759eca45ee85eb6d5a5df61ced }}/pokemonappchallenge:${{ github.sha }}'